export const JuzData = [
  {
    id: 1,
    Juz: 'Juz 1',
    name_arabic: 'آلم',
    name_simple: 'Alif Laam Meem',
    start: 'Al-Fatiha 1',
    end: 'Al-Baqarah 141',
    verses_count: 148,
  },
  {
    id: 2,
    Juz: 'Juz 2',
    name_arabic: 'سيقول السفهاء',
    name_simple: 'Sayaqūl',
    start: 'Al-Baqarah 142',
    end: 'Al-Baqarah 252',
    verses_count: 111,
  },
  {
    id: 3,
    Juz: 'Juz 3',
    name_arabic: 'تلك الرسل',
    name_simple: 'Tilka -r-rusul',
    start: 'Al-Baqarah 253',
    end: 'Al-Imran 92',
    verses_count: 90,
  },
  {
    id: 4,
    Juz: 'Juz 4',
    name_arabic: 'لن تنالوا',
    name_simple: 'Lan Tana Lu',
    start: 'Al-Imran 93',
    end: 'An-Nisaa 23',
    verses_count: 93,
  },
  {
    id: 5,
    Juz: 'Juz 5',
    name_arabic: 'والمحصنات',
    name_simple: 'W-al-muḥṣanāt',
    start: 'An-Nisaa 24',
    end: 'An-Nisaa 147',
    verses_count: 124,
  },
  {
    id: 6,
    Juz: 'Juz 6',
    name_arabic: 'لا يحب الله',
    name_simple: 'Lā yuẖibbu-llāh',
    start: 'An-Nisaa 148',
    end: 'Al-Ma’idah 82',
    verses_count: 88,
  },
  {
    id: 7,
    Juz: 'Juz 7',
    name_arabic: 'وإذا سمعوا',
    name_simple: 'Wa ʾidha samiʿū',
    start: 'Al-Ma’idah 83',
    end: 'Al-An’am 110',
    verses_count: 117,
  },
  {
    id: 8,
    Juz: 'Juz 8',
    name_arabic: 'ولو أننا',
    name_simple: 'Wa law ʾannanā',
    start: 'Al-An’am 111',
    end: 'Al-A’raf 87',
    verses_count: 135,
  },
  {
    id: 9,
    Juz: 'Juz 9',
    name_arabic: 'قال الملأ',
    name_simple: 'Qāl al-malāʾ',
    start: 'Al-A’raf 88',
    end: 'Al-AnfAl-40',
    verses_count: 127,
  },
  {
    id: 10,
    Juz: 'Juz 10',
    name_arabic: 'واعلموا',
    name_simple: 'W-aʿlamū',
    start: 'Al-Anfal-41',
    end: 'At-Tauba 93',
    verses_count: 135,
  },
  {
    id: 11,
    Juz: 'Juz 11',
    name_arabic: 'يعتذرون',
    name_simple: 'Yaʾtadhirūna',
    start: 'At Tauba 94',
    end: 'Hud 5',
    verses_count: 129,
  },
  {
    id: 12,
    Juz: 'Juz 12',
    name_arabic: 'ومامن دابة',
    name_simple: 'Wa mā min dābbah',
    start: 'Hud 6',
    end: 'Yusuf 52',
    verses_count: 123,
  },
  {
    id: 13,
    Juz: 'Juz 13',
    name_arabic: 'وما أبرئ',
    name_simple: 'Wa mā ʾubarriʾu',
    start: 'Yusuf 53',
    end: 'Al-Hijr 1',
    verses_count: 118,
  },
  {
    id: 14,
    Juz: 'Juz 14',
    name_arabic: 'ربما',
    name_simple: 'Ruba Maʾ',
    start: 'Al-Hijr 2',
    end: 'An-Nahl 128',
    verses_count: 135,
  },
  {
    id: 15,
    Juz: 'Juz 15',
    name_arabic: 'سبحٰن الذیٓ',
    name_simple: 'Subḥāna -lladhi',
    start: 'Al-Israa 1',
    end: 'Al-Kahf 74',
    verses_count: 99,
  },
  {
    id: 16,
    Juz: 'Juz 16',
    name_arabic: 'قال ألم',
    name_simple: 'Qāla ʾa-lam',
    start: 'Al-Kahf 75',
    end: 'Ta-Ha 135',
    verses_count: 269,
  },
  {
    id: 17,
    Juz: 'Juz 17',
    name_arabic: 'اقترب للناس',
    name_simple: 'Iqtaraba li-n-nās',
    start: 'Al-Anbiyaa 1',
    end: 'Al-Hajj 78',
    verses_count: 190,
  },
  {
    id: 18,
    Juz: 'Juz 18',
    name_arabic: 'قد أفلح',
    name_simple: 'Qad ʾaflaḥa',
    start: 'Al-Muminun 1',
    end: 'Al-Furqan 20',
    verses_count: 202,
  },
  {
    id: 19,
    Juz: 'Juz 19',
    name_arabic: 'وقال الذين',
    name_simple: 'Wa-qāla -lladhīna',
    start: 'Al-Furqan 21',
    end: 'An-Naml 59',
    verses_count: 339,
  },
  {
    id: 20,
    Juz: 'Juz 20',
    name_arabic: 'امن خلق',
    name_simple: 'Amman khalaqa',
    start: 'An-Naml 60',
    end: 'Al-Ankabut 44',
    verses_count: 171,
  },
  {
    id: 21,
    Juz: 'Juz 21',
    name_arabic: 'اتل مآ اوحی',
    name_simple: 'Otlu maa oohiya',
    start: 'Al-Ankabut 45',
    end: 'Al-Ahzab 30',
    verses_count: 178,
  },
  {
    id: 22,
    Juz: 'Juz 22',
    name_arabic: 'ومن يقنت',
    name_simple: 'Wa-man yaqnut',
    start: 'Al-Ahzab 31',
    end: 'Ya-Sin 21',
    verses_count: 169,
  },
  {
    id: 23,
    Juz: 'Juz 23',
    name_arabic: 'ومالی',
    name_simple: 'Wama liya',
    start: 'Ya-Sin 22',
    end: 'Az-Zumar 31',
    verses_count: 357,
  },
  {
    id: 24,
    Juz: 'Juz 24',
    name_arabic: 'فمن أظلم',
    name_simple: 'Fa-man ʾaẓlamu',
    start: 'Az-Zumar 32',
    end: 'Fussilat 46',
    verses_count: 175,
  },
  {
    id: 25,
    Juz: 'Juz 25',
    name_arabic: 'إليه يرد',
    name_simple: 'ʾIlaihi yuraddu',
    start: 'Fussilat 47',
    end: 'Al-Jathiya 37',
    verses_count: 246,
  },
  {
    id: 26,
    Juz: 'Juz 26',
    name_arabic: 'حـم',
    name_simple: 'Ḥāʾ Mīm',
    start: 'Al-Ahqaf 1',
    end: 'Az-Zariyat 30',
    verses_count: 195,
  },
  {
    id: 27,
    Juz: 'Juz 27',
    name_arabic: 'قال فما خطبكم',
    name_simple: 'Qāla fa-mā khatbukum',
    start: 'Az-Zariyat 31',
    end: 'Al-Hadid 29',
    verses_count: 399,
  },
  {
    id: 28,
    Juz: 'Juz 28',
    name_arabic: 'قد سمع اللہ',
    name_simple: 'Qad samiʿa -llāhu',
    start: 'Al-Mujadila 1',
    end: 'At Tahrim 12',
    verses_count: 137,
  },
  {
    id: 29,
    Juz: 'Juz 29',
    name_arabic: 'تبٰرک الذی',
    name_simple: 'Tabāraka -lladhi',
    start: 'Al-Mulk 1',
    end: 'Al-Mursalat 50',
    verses_count: 431,
  },
  {
    id: 30,
    Juz: 'Juz 30',
    name_arabic: 'عمّ',
    name_simple: 'Amma',
    start: 'An Nabaa 1',
    end: 'An-Nas 6',
    verses_count: 564,
  },
];
