import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  graphic: {
    height: 117,
    overflow: "hidden",
    width: 375,
  },
  scrollContainer: {
    paddingLeft: 20,
    paddingRight: 20,
  },
  
  overlapWrapper: {
    height: 117,
    width: 822,
  },
  overlap: {
    height: 117,
    position: "relative",
    width: 826,
  },
  container: {
    height: 117,
    left: 0,
    position: "absolute",
    top: 0,
    width: 826,
  },
  overlapGroup: {
    height: 117,
    left: 0,
    position: "absolute",
    top: 0,
    width: 500,
  },
  vector: {
    position: "absolute",
    top: 6,
    left: 0,
    width: 500,
    height: 105,
  },
  img: {
    position: "absolute",
    top: 6,
    left: 0,
    width: 237,
    height: 77,
  },
  frameWrapper: {
    position: "absolute",
    top: 0,
    left: 168,
    width: 14,
    height: 14,
    backgroundColor: "#ffffff", // --greywhite
    borderRadius: 7,
    borderWidth: 1.69,
    borderColor: "rgba(34, 63, 122, 1)", // --sleep-500
  },
  frame: {
    position: "absolute",
    top: 2,
    left: 2,
    width: 7,
    height: 7,
  },
  ellipse2: {
    position: "absolute",
    top: 58,
    left: 30,
    width: 14,
    height: 14,
    backgroundColor: "#ffffff",
    borderRadius: 7,
    borderWidth: 1.69,
    borderColor: "rgba(34, 63, 122, 1)",
  },
  ellipse3: {
    position: "absolute",
    top: 97,
    left: 435,
    width: 14,
    height: 14,
    backgroundColor: "rgba(173, 217, 247, 1)", // --sleep-200
    borderRadius: 7,
  },
  frame2: {
    position: "absolute",
    top: 62,
    left: 34,
    width: 7,
    height: 7,
  },
  imgWrapper: {
    position: "absolute",
    top: 83,
    left: 303,
    width: 14,
    height: 14,
    backgroundColor: "rgba(173, 217, 247, 1)", // --sleep-200
    borderRadius: 7,
  },
  frame3: {
    position: "absolute",
    top: 3,
    left: 3,
    width: 7,
    height: 7,
  },
  layerWrapper: {
    position: "absolute",
    top: 104,
    left: 359,
    width: 14,
    height: 14,
    backgroundColor: "rgba(173, 217, 247, 1)",
    borderRadius: 7,
  },
  layer: {
    position: "absolute",
    top: 3,
    left: 3,
    width: 8,
    height: 8,
  },
  group2: {
    position: "absolute",
    top: 100,
    left: 437,
    width: 9,
    height: 7,
  },
  group3: {
    position: "absolute",
    top: 3,
    left: 0,
    width: 9,
    height: 4,
    backgroundColor: "transparent",
  },
  vector2: {
    position: "absolute",
    top: 0,
    left: 6,
    width: 3,
    height: 3,
  },
  maghrib: {
    position: "absolute",
    top: 28,
    left: 267,
    color: "#000000",
    fontSize: 5.7,
    fontFamily: "Raleway-Medium",
    fontWeight: "500",
    letterSpacing: 0.11,
    textAlign: "center",
  },
  timeText: {
    position: "absolute",
    top: 36,
    left: 268,
    color: "#000000",
    fontSize: 5.7,
    fontFamily: "Raleway-Bold",
    fontWeight: "700",
    letterSpacing: 0.11,
    textAlign: "center",
  },
  overlapGroup2: {
    position: "absolute",
    top: 1,
    left: 501,
    width: 321,
    height: 83,
  },
  vector3: {
    position: "absolute",
    top: 5,
    left: 0,
    width: 321,
    height: 78,
  },
  ellipse4: {
    position: "absolute",
    top: 60,
    left: 17,
    width: 14,
    height: 14,
    backgroundColor: "#ffffff",
    borderRadius: 7,
    borderWidth: 1.69,
    borderColor: "rgba(34, 63, 122, 1)",
  },
  frame4: {
    position: "absolute",
    top: 63,
    left: 20,
    width: 7,
    height: 7,
  },
  ellipse5: {
    position: "absolute",
    top: 0,
    left: 140,
    width: 14,
    height: 14,
    backgroundColor: "#ffffff",
    borderRadius: 7,
    borderWidth: 1.69,
    borderColor: "rgba(34, 63, 122, 1)",
  },
  frame5: {
    position: "absolute",
    top: 3,
    left: 144,
    width: 7,
    height: 7,
  },
  group4: {
    position: "absolute",
    top: 46,
    left: 262,
    width: 21,
    height: 21,
    backgroundColor: "rgba(173, 217, 247, 1)",
    borderRadius: 11,
  },
  frame6: {
    position: "absolute",
    top: 5,
    left: 5,
    width: 10,
    height: 10,
  },
});
